version: "3.9"

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    image: docker.io/samjin97/dva-backend:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    image: docker.io/samjin97/dva-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
