name: CI Pipeline + Deploy

on:
  push:
    branches: [ ops ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/worflows/**'
  pull_request:
    branches: [ ops ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'docker-compose.yml'
      - '.github/worflows/**'
  workflow_dispatch:

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml
    with:
      image_name: dva-backend

  frontend:
    uses: ./.github/workflows/frontend-ci.yml
    with:
      image_name: dva-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./*"
          target: ~/dream-vacation-app

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dream-vacation-app
            docker compose pull
            docker compose up -d --remove-orphans
