name: Deploy to EC2

on:
  workflow_run:
    workflows: [ "Frontend CI", "Backend CI" ]
    branches: [ ops ]
    types: [completed]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./*
          target: ~/dream-vacation-app

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dream-vacation-app
            docker compose pull
            docker compose up -d --remove-orphans

